name: vale
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4   

    - name: Vale
      uses: errata-ai/vale-action@v1.4.0
      with:
        config: https://raw.githubusercontent.com/manifoldfinance/documentation/master/CI/vale/.vale.ini
        files: docs/
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create issue using REST API
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
